### ISSUE TITLE
Move export settings to a separate dialog

### ISSUE THREAD

**Issue by nyalldawson** [timlinux/QGISAnimationWorkbench#14]
Instead of the current workflow of setting up all animation and export properties in the dialog and clicking "run", I'd suggest we split the animation settings from the export settings entirely, and go with:

1. The main dialog only contains animation related settings (render mode, zoom ranges, frame counts, (soundtrack?), removing the output options group and output destination widget. Then we change the "Run" button to a separate "Export..." button
2. The export button opens first a file save as dialog (with filters set for the mp4/gif formats), asking the user to pick the export destination. If they pick one, then we open a new "Export settings" dialog, which contains the format choice, and new export specific settings such as video size / compression options /etc.

This would then match the workflow used elsewhere in QGIS, eg. in the layout designer exports.

**Comment by timlinux** [comment]
Sounds like a good approach, I will have a go at doing that. Thanks
