### ISSUE TITLE
Expose to/from feature variables for map rendering too

### ISSUE THREAD

**Issue by nyalldawson** [timlinux/QGISAnimationWorkbench#21]
Currently these variables are only usable for the data defined min scale option -- we should also make them available for map rendering (eg geometry generators) during the fly stage.

**Comment by nyalldawson** [comment]
This should be fixed now

**Comment by timlinux** [comment]
Fly + Hover stage?

**Comment by nyalldawson** [comment]
Fly, not hover. In hover state you'd just use $currentfeature

**Comment by timlinux** [comment]
Even hovering it would be useful to know wherever we came from and are going to. Imagine arrows point into and away from the symbol.
