### ISSUE TITLE
python error on easing_preview.py

### ISSUE THREAD

**Issue by thomas-szczurek** [timlinux/QGISAnimationWorkbench#81]
Got this error every-time I try to use the plugin where one function should be provided with 2 arguments but got one. The plugin gui works but no movie file is created after running the plugin.

conda Qgis 3.36
python 3.12
os fedora 39

![animation_python_error](https://github.com/timlinux/QGISAnimationWorkbench/assets/121474664/78a9e9bd-a457-4253-aafc-2dca0d37acb5)

**Comment by deloverov** [comment]
I have the same error right after opening the plugin interface:

An error has occurred while executing Python code: 

TypeError: isinstance expected 2 arguments, got 1 
Traceback (most recent call last):
  File "/home/boogie/.local/share/QGIS/QGIS3/profiles/default/python/plugins/animation_workbench/easing_preview.py", line 45, in interpolated
    if not isinstance(from_point) == QPoint:
           ^^^^^^^^^^^^^^^^^^^^^^
TypeError: isinstance expected 2 arguments, got 1


Python version: 3.11.2 (main, Apr 28 2025, 14:11:48) [GCC 12.2.0] 
QGIS version: 3.44.6-Solothurn Solothurn, fb066c58058 

Python Path:
/usr/share/qgis/python
/home/boogie/.local/share/QGIS/QGIS3/profiles/default/python
/home/boogie/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python311.zip
/usr/lib/python3.11
/usr/lib/python3.11/lib-dynload
/usr/local/lib/python3.11/dist-packages
/usr/lib/python3/dist-packages
/usr/lib/python3.11/dist-packages
/home/boogie/.local/share/QGIS/QGIS3/profiles/default/python
/home/boogie/.local/share/QGIS/QGIS3/profiles/default/python/plugins/mmqgis/forms
/home/boogie/.local/share/QGIS/QGIS3/profiles/default/python/plugins/linz-data-importer
/home/boogie/Documents/GIS/Animation
